### ISSUE TITLE
Readme Link broken

### ISSUE THREAD

**Issue by OfficialCRUGG** [hopinc/leap_client_rs#1]
In the first paragraph of the Readme, the name "Leap Edge" is a link. But that Link is broken and I get forwarded to https://docs.hop.io/getting-started/introduction instead.

**Comment by pxseu** [comment]
oh totally forgot about it whilst I changed it the repo description

**Comment by pxseu** [comment]
Fixed in 725249485ce1491724fc6ed6aa419a57641f467f
